"""
Day 21: Retries - Idempotency Key Demonstration
===============================================

Educational code demonstrating how Idempotency Keys make retries safe.
NOTE: This code is for learning purposes and is not production-ready.

Concept:
A network timeout is ambiguous:
  - Did the request fail before reaching the server?
  - Or did the server process the request, but the response was lost on the network?

If a client blindly retries a non-idempotent operation (like `POST /charge`), the customer
may be double-charged. An Idempotency Key is a unique token generated by the client for a
specific intent. The server stores key processing results. On retries with the same key,
the server returns the previous cached result without re-executing the operation.
"""

import uuid
import time
from typing import Dict, Any, Optional


class PaymentService:
    """
    Simulates a Payment Gateway with an in-memory Idempotency Store.
    """
    def __init__(self):
        self.account_balance = 1000.0
        # In-memory store mapping idempotency_key -> cached_response
        self.idempotency_store: Dict[str, Dict[str, Any]] = {}
        # Simple execution counter for verification
        self.actual_debits_executed = 0

    def process_charge(self, amount: float, idempotency_key: Optional[str] = None) -> Dict[str, Any]:
        """
        Processes a charge on the account.
        If an idempotency_key is provided:
          - If key exists in store: Returns cached response (Does NOT debit twice).
          - If key is new: Debits account and stores result.
        If NO idempotency key is provided:
          - Debits account every single time!
        """
        if idempotency_key:
            if idempotency_key in self.idempotency_store:
                print(f"  [Payment Service] Idempotency Key '{idempotency_key}' found! Returning cached response.")
                cached_res = self.idempotency_store[idempotency_key].copy()
                cached_res["replayed"] = True
                return cached_res

        # Execute business logic (Debit)
        self.actual_debits_executed += 1
        self.account_balance -= amount
        
        response = {
            "status": "SUCCESS",
            "transaction_id": f"txn_{uuid.uuid4().hex[:8]}",
            "amount_charged": amount,
            "remaining_balance": self.account_balance,
            "replayed": False
        }

        if idempotency_key:
            self.idempotency_store[idempotency_key] = response

        return response


if __name__ == "__main__":
    print("=" * 65)
    print("   DISTRIBUTED SYSTEMS HANDBOOK: IDEMPOTENCY KEY DEMO")
    print("=" * 65)

    payment_service = PaymentService()

    print("\n--- SCENARIO 1: Retrying WITHOUT an Idempotency Key (UNSAFE) ---")
    print(f"Initial Account Balance: INR {payment_service.account_balance:.2f}")

    print("\n[Attempt #1] Client requests: Charge INR 100 (No Idempotency Key)")
    res1 = payment_service.process_charge(amount=100.0, idempotency_key=None)
    print(f"  Response: {res1}")
    print("  [Network Event] Response lost in transit! Client timed out waiting for ACK.")

    print("\n[Attempt #2] Client retries: Charge INR 100 (No Idempotency Key)")
    res2 = payment_service.process_charge(amount=100.0, idempotency_key=None)
    print(f"  Response: {res2}")

    print(f"\nResult Scenario 1: Total Debits Executed = {payment_service.actual_debits_executed}")
    print(f"Current Balance: INR {payment_service.account_balance:.2f} (CUSTOMER DOUBLE CHARGED!)")

    print("\n" + "-" * 65)

    # Reset service
    payment_service = PaymentService()
    idempotency_token = f"idemp_{uuid.uuid4().hex[:8]}"

    print("\n--- SCENARIO 2: Retrying WITH an Idempotency Key (SAFE) ---")
    print(f"Initial Account Balance: INR {payment_service.account_balance:.2f}")

    print(f"\n[Attempt #1] Client requests: Charge INR 100 (Key: {idempotency_token})")
    res1 = payment_service.process_charge(amount=100.0, idempotency_key=idempotency_token)
    print(f"  Response: {res1}")
    print("  [Network Event] Response lost in transit! Client timed out waiting for ACK.")

    print(f"\n[Attempt #2] Client retries: Charge INR 100 (Same Key: {idempotency_token})")
    res2 = payment_service.process_charge(amount=100.0, idempotency_key=idempotency_token)
    print(f"  Response: {res2}")

    print(f"\nResult Scenario 2: Total Debits Executed = {payment_service.actual_debits_executed}")
    print(f"Current Balance: INR {payment_service.account_balance:.2f} (EXACTLY ONCE CHARGED!)")
